### PR TITLE
Loading Chest in BaselineOfNewTools: Integration of Chest as a debugger extension

### PR DESCRIPTION
**Pull request by adri09070**
Link to repository for documentation:

https://github.com/adri09070/Chest

### CODE REVIEW

**Comment by adri09070** [comment]
I don't understand why it doesn't work. I should look at what Metacello object is used to load baselines

**Comment by demarey** [comment]
Thanks for the PR.
2 comments: 
- we cannot include in Pharo Core a project hosted in a personal repository. You should probably transfer it to pharo-spec organization.
- the baseline formatting is lost. It should be fixed.

**Comment by adri09070** [comment]
I recovered the formatting. However, what lost it is the formatting command with CMD+SHIFT+F...

**Comment by StevenCostiou** [comment]
Is the failing test related?

**Comment by adri09070** [comment]
No, there are known issues on the Pharo CI at the moment but I don't know if the integration of Chest has been accepted by the Pharo consortium

**Comment by StevenCostiou** [comment]
Unrelated failing test.

**Comment by StevenCostiou** [comment]
Menu entries should be under debugging menu and not on the top level-menu.

**Comment by adri09070** [comment]
This is done.

The failing test is unrelated

**Comment by estebanlm** [comment]
sorry, now I have a conflict in the baseline, can you fix it?

**Comment by adri09070** [comment]
The conflict is resolved

**Pull request merged**
