### PR TITLE
Refactoring of the `StDebugger` layout from class side to instance side to make it dynamic

### LINKED ISSUE #363: Refactor the debugger so that it uses a dynamic layout with spec
In the debugger presenter (StDebugger), the layout is defined statically with class methods.

Spec 2 provides more simple ways to do it dynamically, on the instance side. This would make the debugger's GUI more extensible

As a result, all methods in the '#specs' category and in the '#layout' category should be moved from class side to instance side to use a dynamic layout.

### PR DESCRIPTION
**Pull request by adri09070**
Fixes #363 
Using the old Spec API, the `StDebugger` layout was defined statically, on class side.

Now, it is defined dynamically on instance side, thanks to the new Spec2 API.

In the future, it will be useful to dynamically update the debugger layout each time a debugger extension is action/desactivated

### CODE REVIEW

**Comment by adri09070** [comment]
The CI fails due to a test class that was testing the mechanism to choose the spec selector to use for the `StDebugger` layout.

Now that the debugger layout is dynamic, this mechanism doesn't exist anymore, as it only relies on the `stackAndCodeContainer` layout. So, in my opinion, this test class should be removed.

**Comment by StevenCostiou** [comment]
@adri09070 Tests should be updated.
I guess for now they could be removed since you removed the logic.
By default, make sure the extension column is deactivated.

**Comment by StevenCostiou** [comment]
> The CI fails due to a test class that was testing the mechanism to choose the spec selector to use for the `StDebugger` layout.
> 
> Now that the debugger layout is dynamic, this mechanism doesn't exist anymore, as it only relies on the `stackAndCodeContainer` layout. So, in my opinion, this test class should be removed.

Ah, sorry, I wrote my previous message before reading your comment.
Yes I think you are right.

**Comment by StevenCostiou** [comment]
> By default, make sure the extension column is deactivated.

By reviewing the changes, i also saw that this is already done :)

**Comment by adri09070** [comment]
I deleted the test class and an usused class variable in StDebugger and now tests pass

**Comment by MarcusDenker** [comment]
There is now a conflict

**Comment by adri09070** [comment]
It was just a conflict between two different methods that can coexist.
It doesn't look like the failing test concerns me

**Review by MarcusDenker — APPROVED** [review]

**Pull request merged**
