### PR TITLE
Adding new rewrite tools

### PR DESCRIPTION
**Pull request by jordanmontt**
This PR adds the Rewriter Tools. Also has two backends for doing the transformations. One can use either `RB` or `Renraku`

It has the rewriter
Capture d’écran 2023-02-10 à 17 16 55

Scope selector that allows to apply the transformations to custom classes
Capture d’écran 2023-02-10 à 17 17 18

Match Tool 
Capture d’écran 2023-02-10 à 17 13 10

Expression Browser
Capture d’écran 2023-02-10 à 17 13 46

Ocurrences Browser
Capture d’écran 2023-02-10 à 17 14 59

Example rules ready to be used
Capture d’écran 2023-02-10 à 17 15 23

Explanation about Rewrite Rules
Capture d’écran 2023-02-10 à 17 13 21

### CODE REVIEW

**Comment by estebanlm** [comment]
PR is ok. 
but beware! 
Including it here does not means it will be loaded in Pharo. You need an extra step for it :)

**Comment by jordanmontt** [comment]
Which is that step? :)

I already edited the baseline to include the tools

**Comment by estebanlm** [comment]
the baseline of Pharo :)

**Comment by jordanmontt** [comment]
Nop, I just tested and it is included in Pharo

**Pull request merged**
