### PR TITLE
adding test to ensure it is possible to recompile code within a bloc with a dead home context twice

### LINKED ISSUE #722: [Debugger][P12] Recompiling code within a bloc cannot be done more than once in the debugger
If you have a bloc closure like this, called via a method

```Smalltalk
MyClass>>mySortBlock

	^ [ :a :b | a < b ]
```

Then, you can paste this code in a playground and debug it (with one `stepOver` and one `stepInto`:

```Smalltalk
anObject := MyClass new.
anObject mySortBlock value: 1 value: 2
```

In the debugger, try to modify the code of the bloc, for example by adding a halt:

```Smalltalk
MyClass>>mySortBlock

      ^ [ :a :b | self halt.  a < b ]
```

 and save the changes.

A popup will open, click on "Compile and browse".

A browser will then open on the embedding method with the new code:

image

Close this browser.

Then, in the debugger, change the code in the bloc again, for example by commenting the halt you've just added:

```Smalltalk
MyClass>>mySortBlock

      ^ [ :a :b | "self halt."  a < b ]
```

Save the changes, confirm the popup by clicking "compile and browse".

A browser opens on the method that hasn't been modified: the halt isn't commented:

image

**Expected behavior:**

The method should have been recompiled with the new code (i.e: with the commented halt)

### PR DESCRIPTION
**Pull request by adri09070**
Fixes #722

Test corresponding to this PR that needs to be merged first: https://github.com/pharo-project/pharo/pull/16319

### CODE REVIEW

**Comment by adri09070** [comment]
@StevenCostiou

**Comment by Ducasse** [comment]
Hi @adri09070 
This test is failing 

```
StDebuggerActionModelTest
 ✗ #testRecompileMethodToInBlockContextWithDeadHomeTwice (7ms)
TestFailure: Got 'methodWithDeadBlockContext

	^ [ (1 + 1) printString ] yourself' instead of 'methodWithDeadBlockContext

	^ [ (1 + 1) printString ] yourself yourself'.
StDebuggerActionModelTest(TestAsserter)>>assert:description:resumable:
StDebuggerActionModelTest(TestAsserter)>>assert:description:
StDebuggerActionModelTest(TestAsserter)>>assert:equals:
StDebuggerActionModelTest>>testRecompileMethodToInBlockContextWithDeadHomeTwice ...assert: (self class >> #methodWithDeadBlockContext) ast sourceCode
		equals: methodWithBlockContextOriginalSource , ' yourself yourself'
StDebuggerActionModelTest(TestCase)>>performT
```

**Comment by adri09070** [comment]
Hi @Ducasse 

Yes, this is because https://github.com/pharo-project/pharo/pull/16319 should be merged first. That's why I put it to draft

**Comment by Ducasse** [comment]
Kicking the build again

**Comment by Ducasse** [comment]
This is strange since I integrated https://github.com/pharo-project/pharo/pull/16319

**Comment by Ducasse** [comment]
May be https://github.com/pharo-project/pharo/pull/16319 is not available yet?

**Comment by adri09070** [comment]
Yes, I don't think https://github.com/pharo-project/pharo/pull/16319 is available yet.
Moreover, [the other PR](https://github.com/pharo-project/pharo/pull/16319) has been merged into Pharo13 and this PR targets Pharo12.
 Both PRs should be merged into Pharo13 and Pharo12.

You can change the target branch of this PR to Pharo13 (I have the rights to do it, but I don't find the button to do it on Github) and if the test passes, you could later merge both PRs into Pharo12

**Comment by adri09070** [comment]
Ah, I found the button

**Comment by adri09070** [comment]
But we still need https://github.com/pharo-project/pharo/pull/16319 to be available. I don't know when new Pharo builds are built

**Comment by Ducasse** [comment]
Let us wait a bit and see.

**Comment by Ducasse** [comment]
I do not understand because the test is failing

```
StDebuggerActionModelTest
 ✗ #testRecompileMethodToInBlockContextWithDeadHomeTwice (5ms)
```

**Comment by adri09070** [comment]
We just had to wait for the next Pharo build. The NewTools CI does not create a full image with the bootstrap.

Failing test is unrelated

**Pull request merged**
