### PR TITLE
Added debugger tests when accepting code with unknown variables

### PR DESCRIPTION
**Pull request by guillep**
Testing cases when:
 - choosing to leave variable undeclared
 - defining a class
 - defining a trait
 - defining a global
 - cancelling

Tests cover regressions of the case https://github.com/pharo-project/pharo/pull/9926

### CODE REVIEW

**Comment by guillep** [comment]
Tests failing in Pharo 10 because of the original issue pharo-project/pharo#9926

`RubEditingArea>>doesNotUnderstand: #isForScripting`

Showing that it is able to reproduce the issue :)

**Comment by estebanlm** [comment]
hey, @guillep. I still have some errors here.

**Comment by guillep** [comment]
After merging with the Pharo10 branch I can reproduce the issue. It is caused by this method that is missing a return.

```smalltalk
RubAbstractSmalltalkMode >> isForScripting
	"needs to be unified is #isScripting"
	self isScripting
```

Strange thing: after some debugging, it was rewritten to include the return, but I did nothing!

**Comment by guillep** [comment]
> Strange thing: after some debugging, it was rewritten to include the return, but I did nothing!

Or I fixed it automatically, I cannot recall. But this is broken in latest Pharo 10

**Comment by guillep** [comment]
Tests should be green after merging https://github.com/pharo-project/pharo/pull/10564

**Comment by guillep** [comment]
The remainder is because the message of exceptions is different in interactive and non interactive...

image

**Comment by estebanlm** [comment]
hi @guillep... how do we proceed with this?

**Comment by demarey** [comment]
Probably this PR should target Pharo11 branch. 
Is it ready for merge?

**Comment by Ducasse** [comment]
On P12 

```
stDebuggerTest
 ✗ #testAcceptCodeChangesWithUndefinedClassShouldDefineClass (121ms)
 ✗ #testAcceptCodeChangesWithUndefinedClassShouldDefineTrait (120ms)
```

I'm in favor to accept the PR and fix the tests after. But tell me.

**Comment by estebanlm** [comment]
> Probably this PR should target Pharo11 branch. Is it ready for merge?

Pharo11 branch is more or less dead (except for bugfixes), this needs to be on P12 now.

**Comment by Ducasse** [comment]
Yes I meant for P12

**Comment by Ducasse** [comment]
I do not really know how to solve the conflicts.

**Comment by Ducasse** [comment]
I moved to Pharo13

**Comment by Ducasse** [comment]
I did a new PR where I harvested the tests and skipped three of them.

**Pull request closed without merging**
