### PR TITLE
Improvements to the Scopes Editor and integration with Pharo

### PR DESCRIPTION
**Pull request by carolahp**
### Summary
This PR implements the following:
- It is now possible to create scopes that contain all the classes in a package but not the package itself is now possible
- Scopes created through AND and OR operations are now fully dynamic (They were flattened before)
- Enable integration with Calypso (only for package scopes) and with Refactoring Preview Windows.
- Create tests for the scope behaviors
- Bugs were solved

### Work to be done in the next PR
- Finish the implementation of hierarchy scopes

### CODE REVIEW

**Comment by carolahp** [comment]
Some tests fail because this PR depends on Pharo [PR#15918](https://github.com/pharo-project/pharo/pull/15918)

**Review by tesonep — APPROVED** [review]

**Comment by tesonep** [comment]
Once the PR in Pharo is integrated, we can integrate it

**Comment by Ducasse** [comment]
It is integrated so we can merge this one.

**Comment by Ducasse** [comment]
I relaunched to make sure.

**Comment by tesonep** [comment]
Fix https://github.com/pharo-project/pharo/issues/16329

**Pull request merged**
