### PR TITLE
[P12][Backport] adding test to ensure it is possible to recompile code within a bloc with a dead home context twice

### PR DESCRIPTION
**Pull request by adri09070**
Backport of #723 to Pharo12

Needs https://github.com/pharo-project/pharo/pull/16784 to be merged first

### CODE REVIEW

**Comment by adri09070** [comment]
Fixes #775

**Comment by adri09070** [comment]
unrelated failing test @StevenCostiou

**Comment by Ducasse** [comment]
@estebanlm So could we merge this before adrien leaves?

**Comment by Ducasse** [comment]
This is an important feature to me.

**Comment by estebanlm** [comment]
yep, @StevenCostiou  is the specialist in this area but since is a backport (and a test), I'd say let's go :)

**Pull request merged**
