### PR TITLE
9956 fixes A new method gets make when you try to use the debugger to make a new class

### LINKED ISSUE #9956: A new method gets make when you try to use the debugger to make a new class
**Bug description**
When I have a test and it uses `aNewClass new`   the new class and also a new method is made 

**To Reproduce**
1.  make a test which uses  setUp with `myClass := aNewClass new in it
2.  Press on the dot to run the tests. 
3.  the debugger pops up that the class and a new method cannot be understood
4.  press create 

**Expected behavior**
Only the class schould be made 

**Version information:**
 - OS: Windows 10
 - Version: 
 - Pharo Version  9

### PR DESCRIPTION
**Pull request by StevenCostiou**
Fixes https://github.com/pharo-project/pharo/issues/9956

### CODE REVIEW

**Comment by StevenCostiou** [comment]
I'm not sure if we can consider the tests are passing or not.
I'm not certain the one failing on Pharo-integration are related to my changes.

**Comment by estebanlm** [comment]
it should not.
let's see.

**Comment by estebanlm** [comment]
mmm... I need to remove Pharo9.0 (I thought it was already done). 
In anycase... this is working :)

**Comment by ghost** [comment]
is this also backported to P9 because that one we use for the exercism track ?

**Pull request merged**
