### PR TITLE
adding traces in SpMorphicMillerAdapter to trace problems in CI

### LINKED ISSUE #664: Debugger Tests are breaking the build
Since a monent now we get this on the pharo build log

```
Finished to run tests of NECompletion-Tests in 271 milliseconds 58 microseconds
Beginning to run tests of NewTools-Debugger-Tests with random seed 178220933
NewUndeclaredWarning: StTestDebuggerProvider>>buildDebuggerWithMissingClassContext (MissingClass is Undeclared)
NewUndeclaredWarning: StTestDebuggerProvider>>buildDebuggerWithMissingClassContext (MissingClass is Undeclared)
NewUndeclaredWarning: StTestDebuggerProvider>>buildDebuggerWithMissingClassContext (MissingClass is Undeclared)
SubscriptOutOfBounds: 0 in #()
Array(Object)>>errorSubscriptBounds:
Array(Object)>>at:
[ | size firstMorphIndex |
		size := innerWidget submorphs size.
		firstMorphIndex := size - self presenter visiblePages + 1. 
		self widget showMorph: (innerWidget submorphs at: ((firstMorphIndex max: 1) min: size)) ] in SpMorphicMillerAdapter>>scrollToShowLastPage in Block: [ | size firstMorphIndex |...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
[
		| extraWorldsToDraw |
		extraWorldsToDraw := ExtraWorldListMutex critical: [
			                     self extraWorldList ].
		extraWorldsToDraw do: [ :world | world doOneCycle ].

		(self currentWorld isNotNil and: [
			 (extraWorldsToDraw includes: self currentWorld) not ]) ifTrue: [
			self currentWorld doOneCycle ] ] in WorldMorph class>>doOneCycle in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[ MorphicRenderLoop new doOneCycleWhile: [ true ] ] in MorphicUIManager>>spawnNewProcess in Block: [ MorphicRenderLoop new doOneCycleWhile: [ tru[..]
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....
```

### PR DESCRIPTION
**Pull request by adri09070**
Trying to fix #664

### CODE REVIEW

**Comment by Ducasse** [comment]
do you need it in Pharo or just your PR is enough to get the trace?

**Comment by adri09070** [comment]
This is just for me to investigate so I think the PR should be enough (and if it should be in Pharo, I should do a PR in pharo-spec/Spec instead ). 
I discovered what causes problem here but I don't think this is a debugger problem. This is a problem in Morphic/SpecMorph adapters.

In `SpMorphicMillerAdapter>>#scrollToShowLastPage`, a bloc evaluation is defered which show a submorph of its inner widget. However, *sometimes* its inner widget has no submorph and the adapter tries to show the morph at index 0, which causes this random error on the CI.
I don't think this is something I can control in the debugger. Maybe @estebanlm has an idea as to how the `SpMorphicMillerAdapter`'s inner widget happens to have no submorph ?

**Comment by adri09070** [comment]
Example of CI run that went wrong with traces: https://github.com/pharo-spec/NewTools/actions/runs/7611736592/job/20727806873?pr=665

Example of CI run that went smoothly with traces: https://github.com/pharo-spec/NewTools/actions/runs/7611658534/job/20727565575

Also another example of CI run that went wrong and in which I don't know what the hell happened because there are completely different errors with identical (but less numerous) traces: https://github.com/pharo-spec/NewTools/actions/runs/7611490325/job/20727060848

**Comment by adri09070** [comment]
An ugly solution that could at least fix the CI is to add an `innerWidget submorphs ifNotEmpty:` guard but I'm pretty sure someone familiar with Morphic would be better suited to investigate and fix it

**Comment by Ducasse** [comment]
Let us fix it in a ugly way because there is no Morphic expert and we are working for killing morphic :)

**Comment by estebanlm** [comment]
the problem seems to be a race condition, not *directly* a morphic problem, heh. 
in anycase, I will merge **if you promise to revert as soon as you have the information you need** :)

**Comment by estebanlm** [comment]
> An ugly solution that could at least fix the CI is to add an `innerWidget submorphs ifNotEmpty:` guard but I'm pretty sure someone familiar with Morphic would be better suited to investigate and fix it

you have `Morph>>#hasSubmorphs` method, no need to break demeters law.

**Comment by estebanlm** [comment]
btw, you know you can run smalltalkci locally, isn't?
that may help you to find the problem without charging the real CI

**Comment by adri09070** [comment]
> btw, you know you can run smalltalkci locally, isn't? that may help you to find the problem without charging the real CI

How do you do that?

**Comment by estebanlm** [comment]
> > btw, you know you can run smalltalkci locally, isn't? that may help you to find the problem without charging the real CI
> 
> How do you do that?

you checkout https://github.com/hpi-swa/smalltalkCI and from terminal execute something like:

```shell
./bin/smalltalkci -s Pharo64-12 /home/esteban/dev/repo/pharo-vcs/iceberg/.smalltalk.ston
```

**Comment by adri09070** [comment]
I think I fixed this error, but I now have a different (but similar) one (that was already there:  https://github.com/pharo-spec/NewTools/actions/runs/7603649968/job/20705636397?pr=660)

**Comment by adri09070** [comment]
> > > btw, you know you can run smalltalkci locally, isn't? that may help you to find the problem without charging the real CI
> > 
> > 
> > How do you do that?
> 
> you checkout https://github.com/hpi-swa/smalltalkCI and from terminal execute something like:
> 
> ```shell
> ./bin/smalltalkci -s Pharo64-12 /home/esteban/dev/repo/pharo-vcs/iceberg/.smalltalk.ston
> ```

Well, when I do that, I get an error because the CI image cannot find Sindarin ...

**Comment by adri09070** [comment]
Everything should be good once https://github.com/pharo-spec/Spec/pull/1511 and https://github.com/pharo-project/pharo/pull/16016 will be merged

**Pull request closed without merging**
