### PR TITLE
Major refactoring and fixes in New File Browser

### PR DESCRIPTION
**Pull request by hernanmd**
This PR includes features and major refactorings to the File Browser, including:

- Display bookmarks in FileBrowser and Dialogs.
- Refresh bookmarks when adding or removing.
- When the directory dialog is opened, only directories are shown.
- A lot of duplicated code were removed.
- Better names for methods and instance variables.
- Fixed a test

### CODE REVIEW

**Comment by Ducasse** [comment]
Do you still get the trait bug? because I thought Guille fixed it?
Did you use the latest version?

**Comment by Ducasse** [comment]
We get

```
 ✗ #testObsoleteClasses (673ms)
KeyNotFound: key #bookmarksTreeTable not found in SystemDictionary
```

**Comment by hernanmd** [comment]
> Do you still get the trait bug? because I thought Guille fixed it? Did you use the latest version?

I used the latest version, however I saw #15978 wasn't integrated.
I will check the PR.

**Comment by Ducasse** [comment]
Indeed I saw that the fix of Guille did not get in but basicTraitComposition does not exist so this is normal.

**Comment by Ducasse** [comment]
Did you see we got

```
 ✗ #testObsoleteClasses (673ms)
KeyNotFound: key #bookmarksTreeTable not found in SystemDictionary
```

**Comment by hernanmd** [comment]
> Did you see we got
> 
> ```
>  ✗ #testObsoleteClasses (673ms)
> KeyNotFound: key #bookmarksTreeTable not found in SystemDictionary
> ```

Tests were all green here so I'll keep checking tomorrow

Screenshot 2024-01-22 at 00 38 30

**Comment by hernanmd** [comment]
> Did you see we got
> 
> ```
>  ✗ #testObsoleteClasses (673ms)
> KeyNotFound: key #bookmarksTreeTable not found in SystemDictionary
> ```

Fixed. It was the TraitedClass class side definition problem.

Current failures is not related:
```
ProperMethodCategorizationTest
 ✗ #testNoUncategorizedMethods (15ms)
TestFailure: the following classes have uncategorized methods: an OrderedCollection(IceTipPackageModel class)
ProperMethodCategorizationTest(TestAsserter)>>assert:description:resumable:
ProperMethodCategorizationTest(TestAsserter)>>assert:description:
ProperMethodCategorizationTest>>testNoUncategorizedMethods ...assert: remaining isEmpty description: 'the following classes have uncategorized methods: ' , remaining asString
ProperMethodCategorizationTest(TestCase)>>performTest

ReleaseTest
 ✗ #testThatThereAreNoSelectorsRemain...tAreSentButNotImplemented (696ms)
TestFailure: an OrderedCollection('IceTipCherryPickCommand>>#selectedCommitish' 'IceTipInspectCommand>>#item' 'TIceRepositoryReader classTrait>>#id' 'TIceRepositoryWriter classTrait>>#id') should have been empty
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest(TestAsserter)>>assertEmpty:
ReleaseTest>>testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented ...assertEmpty: (violations difference: knownFailures)
ReleaseTest(TestCase)>>performTest
```

**Comment by hernanmd** [comment]
Thanks!

**Pull request merged**
