### PR TITLE
Deprecate asFileName and re-write senders

### PR DESCRIPTION
**Pull request by hernanmd**
As reported in [this pharo issue](https://github.com/pharo-project/pharo/issues/16123), this PR should be applied along with the [PR in pharo repository](https://github.com/pharo-project/pharo/pull/16169). It is a small PR to clean dependencies which could bring problems when removing old FileList.

### CODE REVIEW

**Comment by Ducasse** [comment]
I have a question why the code is not "as simple as"
`FileReference new withPath: ....`

**Comment by hernanmd** [comment]
> I have a question why the code is not "as simple as" `FileReference new withPath: ....`

Apparently the file name re-"encoding" is just to replace characters such as $/ with $# before saving the file.
It is more a direct translation, but I never used `newWithPath:` so I'd need to check.

**Comment by Ducasse** [comment]
What I means is that if String >> asFileName is doing something too complex it means that such complex behavior should be moved to fileReference so that 
- asFileName can be rewritten in a simpler way 
- users of asfilename can be rewritten simply too. 
So may be the logic of asFileName should be migrated to FileReference

**Review by guillep — APPROVED** [review]
Thanks @hernanmd ! I like the tests.

Reading your tests I wonder why is this `fuelOut` useful... But that's another story

**Comment by jecisc** [comment]
I'm restarting the CI because I have the impression the error is not related

**Comment by Ducasse** [comment]
Hi @hernanmd
Can you have a look because I would like to integrate it?

**Comment by Ducasse** [comment]
@jecisc I wonder if your merging of packages did not impact this PR
can you have a look?

**Comment by hernanmd** [comment]
> Hi @hernanmd Can you have a look because I would like to integrate it?

In #781

**Pull request closed without merging**
