### PR TITLE
Removing dependency to UIManager in StDebugger

### LINKED ISSUE #15430: StDebugger MUST not refer to UIManager
```
requestProtocolIn: aClass

	| entryCompletion applicants choice |
	self class fastTDD ifTrue: [ ^ Protocol unclassified ].
	applicants := self protocolSuggestionsFor: aClass.
	entryCompletion := EntryCompletion new
		                   dataSourceBlock: [ :currText | applicants ];
		                   filterBlock: [ :currApplicant :currText | 
			                   currText size > 3 and: [ 
					                   currApplicant asLowercase includesSubstring:
							                   currText asString asLowercase ] ].

	choice := (UIManager default
		           request:
		           'Start typing for suggestions (3 characters minimum)'
		           initialAnswer: Protocol unclassified
		           title: 'Choose a protocol'
		           entryCompletion: entryCompletion) ifNil: [ Abort signal ].

	^ choice ifEmpty: [ Protocol unclassified ]
```

### PR DESCRIPTION
**Pull request by adri09070**
Fixes https://github.com/pharo-project/pharo/issues/15430

Needs https://github.com/pharo-spec/Spec/pull/1540 to be merged first

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks adrian let us see what esteban will say. @estebanlm

**Comment by estebanlm** [comment]
yes, this is fine but let's wait until the CI is working again (when Pharo13 is added)

**Comment by MarcusDenker** [comment]
I added an issue to the main issue tracker for the CI:

https://github.com/pharo-project/pharo/issues/16589

**Comment by jecisc** [comment]
Test failure not related.

**Comment by Ducasse** [comment]
@adri09070 
Can you have a look at the conflict? I'm taking the lead to merge or close all the pending PRs
because I'm fed up of the message we send around.

**Comment by adri09070** [comment]
This PR can simply be closed without merge. #760 completely removed the method that I changed and it's ok

**Pull request closed without merging**
