### PR TITLE
Fixing Chest's group that should be loaded in the baseline

### PR DESCRIPTION
**Pull request by adri09070**
Right now, nothing is loaded because Chest doesn't specify anything for the 'default' group.

This will load  `Chest`, `Chest-Commands` and `Chest-Tests`

### CODE REVIEW

**Comment by adri09070** [comment]
Still, nothing is loaded... I try to understand why

**Review by StevenCostiou — APPROVED** [review]
Looks good.
I will merge it if the CI passes.

**Comment by adri09070** [comment]
But it's still not good. It still doesn't load Chest and I don't understand why

**Comment by StevenCostiou** [comment]
Can you try removing the 'default' group loading?

**Comment by adri09070** [comment]
It doesn't change anything.

It may be that it is not loaded because nothing that is loaded by default has a dependency to Chest

**Comment by adri09070** [comment]
The only difference I see with Sindarin, which is loaded, is that NewTools-Sindarin-Commands requires the package `Sindarin` and is included in the Debugger group, which is loaded by default

**Comment by adri09070** [comment]
Ok, now it works

**Comment by adri09070** [comment]
Failing test looks unrelated

**Comment by MarcusDenker** [comment]
I looks like it breaks the bootrap (the full image load):

https://github.com/pharo-project/pharo/issues/12926

**Pull request merged**
