### PR TITLE
Debug Point Browser integration

### PR DESCRIPTION
**Pull request by adri09070**
Needs https://github.com/pharo-project/pharo/pull/16177 to be merged first.

This PR integrates the debug points browser, a new tool to visualize and configure existing debug points. (Full details on the new debug point model are described in the PR above)

The tool can be opened via the `Debug > Debug Point Browser` world menu and looks like that: 

image

On the top-left, a table allows to visualize all debug points (breakpoints/watchpoints/etc.)
Each debug point has a name (more a tag than a name) that can be edited directly in this table.
The "enabled" state of the debug point is also displayed, as well as the scope of the debug point (class or object)

All behaviors of the selected can be configured via the right pane of debug point browser

When a debug point is selected, according to the target of the debug point, different information are displayed.
If the target is an AST node, the code of the concerned method is displayed (like in screenshot below), while highlightingthe corresponding code
If the target is an instance variable, all concerned methods are listed and selecting a method display displays the corresponding code and highlights the correct variable accesses:

image

It is possible to filter the displayed debug points by name, thanks to an input field at the top:

image

To set object-centric debug points, the left-most button in the inspector toolbar allows to do the same thing in the same way as current object-centric breakpoints:

image

Last but not least, it is also possible to change the scope of an existing debug point to an object, which was not possible before.
The third button in the inspector toolbar allows to do that and opens a modal to choose a debug point whose scope should be changed to the inspected object:

image

### CODE REVIEW

**Comment by adri09070** [comment]
Maybe this failing test is related, I should investigate: 
`LinkInstallerTest>>#testSlotOrVarLinksRemainAfterMethodModificationForObject`

**Comment by adri09070** [comment]
Needs https://github.com/pharo-project/pharo/pull/16268 to be merged first because it relies on the Calypso package that will be loaded after that PR is merged

**Comment by adri09070** [comment]
To me, this is now  ready for review @StevenCostiou

**Comment by estebanlm** [comment]
the prerequisites are merged. 
I am rerunning the tests.

**Comment by estebanlm** [comment]
failing test is not related. Is @StevenCostiou approves, this can be merged

**Review by StevenCostiou — APPROVED** [review]

**Comment by Ducasse** [comment]
Synced with steven -> ok

**Comment by StevenCostiou** [comment]
There are a lot of changes, but only additions (the browser).
It should be merged and be experimented.
There will not be any impact if it is not used.

**Pull request merged**
